### ISSUE TITLE
Use dynamic protocol fee

### ISSUE THREAD

**Issue by gregdhill** [zenlinkpro/Zenlink-DEX-Module#44]
The protocol fee for swapping is currently hard-coded to 0.3% despite the fact that `FeeMeta` can be set up to 100%. See:
- [`get_amount_in`](https://github.com/zenlinkpro/Zenlink-DEX-Module/blob/0f62f55d549914a6109239473dca38d1dc6d7193/zenlink-protocol/src/swap/mod.rs#L452)
- [`get_amount_out`](https://github.com/zenlinkpro/Zenlink-DEX-Module/blob/0f62f55d549914a6109239473dca38d1dc6d7193/zenlink-protocol/src/swap/mod.rs#L476)

**Comment by byterui** [comment]
SwapFee is fixed. FeeMeta controls the percentage of SwapFee that the admin gets.
